# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\dft\program\VisualScore\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.paramLayout = QtWidgets.QHBoxLayout()
        self.paramLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.paramLayout.setContentsMargins(100, -1, 100, -1)
        self.paramLayout.setSpacing(100)
        self.paramLayout.setObjectName("paramLayout")
        self.paramLayout_1 = QtWidgets.QHBoxLayout()
        self.paramLayout_1.setContentsMargins(-1, -1, 50, -1)
        self.paramLayout_1.setSpacing(20)
        self.paramLayout_1.setObjectName("paramLayout_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.paramLayout_1.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.paramLayout_1.addWidget(self.lineEdit)
        self.paramLayout.addLayout(self.paramLayout_1)
        self.paramLayout_2 = QtWidgets.QHBoxLayout()
        self.paramLayout_2.setContentsMargins(-1, -1, 50, -1)
        self.paramLayout_2.setSpacing(20)
        self.paramLayout_2.setObjectName("paramLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.paramLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.paramLayout_2.addWidget(self.lineEdit_2)
        self.paramLayout.addLayout(self.paramLayout_2)
        self.paramLayout_3 = QtWidgets.QHBoxLayout()
        self.paramLayout_3.setContentsMargins(-1, -1, 50, -1)
        self.paramLayout_3.setSpacing(20)
        self.paramLayout_3.setObjectName("paramLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.paramLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.paramLayout_3.addWidget(self.lineEdit_3)
        self.paramLayout.addLayout(self.paramLayout_3)
        self.verticalLayout.addLayout(self.paramLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setMaximumSize(QtCore.QSize(100, 100))
        self.tableView.setBaseSize(QtCore.QSize(0, 0))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_5.addWidget(self.tableView)
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setMaximumSize(QtCore.QSize(100, 100))
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout_5.addWidget(self.tableView_2)
        self.tableView_3 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_3.setMaximumSize(QtCore.QSize(100, 100))
        self.tableView_3.setObjectName("tableView_3")
        self.horizontalLayout_5.addWidget(self.tableView_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 100))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "不舒适块数量"))
        self.label_2.setText(_translate("MainWindow", "中心亮度差阈值"))
        self.label_3.setText(_translate("MainWindow", "亮度差阈值"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

